apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.external.metrics.k8s.io
spec:
  group: external.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  service:
    name: "{{ .Values.service.name }}"
    namespace: "{{ .Values.service.namespace }}"
    port: 443
  groupPriorityMinimum: 100
  versionPriority: 100