apiVersion: v1
kind: ConfigMap
metadata:
  name: config-models-map
  namespace: {{ include "groundx.ns" . }}
  labels:
    appVersion: {{ .Chart.AppVersion | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    version: {{ .Chart.Version | quote }}
data:
  config_models.py: |
    env = dict(
    )
