apiVersion: v1
kind: ConfigMap
metadata:
  name: layout-gunicorn-conf-py-map
  namespace: {{ include "groundx.ns" . }}
data:
  gunicorn_conf.py: |
    infolog = "-"
    accesslog = "-"
    errorlog = "-"

    loglevel = "{{ .Values.logLevel }}"
    workers = {{ .Values.layout.internal.api.workers }}
    threads = {{ .Values.layout.internal.api.threads }}
    timeout = {{ .Values.layout.internal.api.timeout }}

    worker_class = "uvicorn.workers.UvicornWorker"

    bind = "0.0.0.0:8080"

    wsgi_app = "document_api_server:app"