{{- $ns := include "groundx.ns" . -}}
{{- $inline := .Values.layout.ocr.credentialsInline | default "" -}}
{{- $haveFile := .Files.Get "files/layout/credentials.json" -}}
{{- if or $inline $haveFile }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: layout-ocr-credentials-map
  namespace: {{ $ns }}
data:
  credentials.json: |
    {{- if $inline }}
    {{ $inline | nindent 4 }}
    {{- else }}
    {{ $haveFile | nindent 4 }}
    {{- end }}
{{- end }}