{{- $ns := include "groundx.ns" . -}}
{{- $layout := .Values.layout | default dict -}}
{{- $internal := $layout.internal | default dict -}}
{{- $ocr := $internal.ocr | default dict -}}
{{- $path := $ocr.credentials | default "" -}}

{{- if and $path (not (kindIs "string" $path)) -}}
{{- fail "layout.internal.ocr.credentials must be a string path to a file packaged in the chart (e.g., files/ocr/credentials.json)" -}}
{{- end -}}

{{- if and (kindIs "string" $path) (ne $path "") -}}
  {{- $matches := .Files.Glob $path -}}
  {{- if not $matches -}}
    {{- fail (printf "layout.internal.ocr.credentials file not found at path: %s" $path) -}}
  {{- end -}}
  {{- $blob := .Files.Get $path -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: layout-ocr-credentials-map
  namespace: {{ $ns }}
data:
  credentials.json: |
    {{ $blob | nindent 4 }}
{{- end }}