apiVersion: v1
kind: ConfigMap
metadata:
  name: ranker-gunicorn-conf-py-map
  namespace: {{ include "groundx.ns" . }}
  labels:
    appVersion: {{ .Chart.AppVersion | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    version: {{ .Chart.Version | quote }}
data:
  gunicorn_conf.py: |
    infolog = "-"
    accesslog = "-"
    errorlog = "-"

    loglevel = "{{ .Values.logLevel }}"
    workers = {{ .Values.ranker.internal.api.workers }}
    threads = {{ .Values.ranker.internal.api.threads }}
    timeout = {{ .Values.ranker.internal.api.timeout }}
    timeout_keep_alive = 15

    worker_class = "uvicorn.workers.UvicornWorker"

    bind = "0.0.0.0:8080"

    wsgi_app = "ranker_server:app"
