{{- $ns := include "groundx.ns" . -}}
{{- $workers := int (default 1 .Values.summary.internal.inference.workers) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: summary-supervisord-conf-map
  namespace: {{ include "groundx.ns" . }}
  labels:
    appVersion: {{ .Chart.AppVersion | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    version: {{ .Chart.Version | quote }}
data:
  supervisord.conf: |
    [supervisord]
    nodaemon=true
    logfile=/dev/null
    {{- range $i, $_ := until $workers }}

    [program:celery_worker_{{ add $i 1 }}]
    command=celery -A summary.celery_inference.appSummary worker -n %(ENV_POD_NAME)s-w{{ add $i 1 }} --loglevel=INFO --concurrency={{ $.Values.summary.internal.inference.threads }} --queues=summary_inference_queue --pool=solo
    environment=
      CELERY_WORKER_NAME="%(ENV_POD_NAME)s-w{{ add $i 1 }}",
      LOCAL="0",
      PYTHONUNBUFFERED="1"
    autostart=true
    autorestart=true
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0
    {{ end }}
    [program:celery_monitor]
    command=python /workspace/summary_monitor.py
    environment=
      LOCAL="0",
      PYTHONUNBUFFERED="1"
    autostart=true
    autorestart=true
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0

    [program:celery_health]
    command=python /workspace/summary_health.py
    environment=
      LOCAL="0",
      PYTHONUNBUFFERED="1"
    autostart=true
    autorestart=true
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0
