groundxKey: "00000000-0000-0000-0000-000000000000"

admin:
  apiKey: "00000000-0000-0000-0000-000000000000"
  email: "support@mycorp.net"
  password: "password"
  username: "00000000-0000-0000-0000-000000000000"

cluster:
  pvClass: eyelevel-pv

  # "", "eks", "aks", "gke", "openshift", etc.
  type: eks

db:
  enabled: true

  dbName: eyelevel
  username: eyelevel
  password: password

  privilegedUsername: root
  privilegedPassword: password

file:
  enabled: true

  bucketName: eyelevel

  username: minio
  password: minio123

search:
  enabled: true

  indexName: prod-1
  username: eyelevel
  password: R0otb_*t!kazs
  privilegedUsername: admin
  privilegedPassword: R0otb_*t!kazs
