targetHost: ""
intervalSeconds: 10
successLogEvery: 6
queryTimeoutSeconds: 2
slowThresholdSeconds: 2
image:
  repository: public.ecr.aws/docker/library/python
  tag: 3.12-alpine
resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi
