apiVersion: v2
name: groundx
description: "GroundX RAG on Prem: Secure, Accurate, Scaled"
version: 0.1.0
appVersion: 0.1.0
home: https://www.eyelevel.ai/
sources:
- https://github.com/eyelevelai/groundx-on-prem
maintainers:
- name: GroundX Project Maintainers
  email: developer@groundx.ai
dependencies:
  - name: pxc-operator
    alias: dbOperator
    repository: https://percona.github.io/percona-helm-charts
    version: 1.18.0
    condition: db.enabled
  - name: operator
    alias: file
    repository: https://operator.min.io
    version: 6.0.3
    condition: file.enabled
  - name: opensearch
    alias: search
    repository: oci://public.ecr.aws/c9r4x6y5/helm
    version: 0.1.1
    condition: search.enabled
