{{- if eq (include "groundx.google.managed" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "groundx.google.secretName" . }}
  namespace: {{ include "groundx.ns" . }}
  labels:
{{ include "groundx.renderDefaultLabels" (dict "name" "" "indent" 4 "root" $) }}
stringData:
  credentials.json: |
{{ include "groundx.google.credentials" . | indent 4 }}
{{- end }}
