{{- $ic := include "groundx.workspace.api.create" . -}}
{{- if eq $ic "true" }}
{{- $svc := include "groundx.workspace.serviceName" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $svc }}-gunicorn-conf-py-map
  namespace: {{ include "groundx.ns" . }}
  labels:
{{ include "groundx.renderDefaultLabels" (dict "name" "" "indent" 4 "root" $) }}
data:
  gunicorn_conf.py: |
    accesslog = "-"
    errorlog = "-"
    loglevel = {{ include "groundx.logLevel" . | quote }}
    timeout = {{ include "groundx.workspace.api.timeout" . }}
    timeout_keep_alive = {{ include "groundx.workspace.api.timeoutKeepAlive" . }}
    worker_class = "uvicorn.workers.UvicornWorker"
    workers = {{ include "groundx.workspace.api.workers" . }}
    threads = {{ include "groundx.workspace.api.threads" . }}
    bind = "0.0.0.0:{{ include "groundx.workspace.api.containerPort" . }}"
    wsgi_app = "server:app"
{{- end }}
