apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: groundx-studio-dev
resources:
  - namespace.yaml
configMapGenerator:
  - name: workspace-db-ca
    files:
      - rds-us-east-1-bundle.pem
generatorOptions:
  disableNameSuffixHash: true
