nodeSelector:
  node: eyelevel-cpu
replicas: 1

image:
  registry: cgr.dev
  repository: eyelevel.ai
  name: strimzi-kafka-operator
  tag: v0.50.1
  imagePullSecrets:
    - name: chainguard-pull-secret

kafka:
  image:
    registry: cgr.dev
    repository: eyelevel.ai
    name: strimzi-kafka
    tagPrefix: v0.50.1
kafkaConnect:
  image:
    registry: cgr.dev
    repository: eyelevel.ai
    name: strimzi-kafka
    tagPrefix: v0.50.1
topicOperator:
  image:
    registry: cgr.dev
    repository: eyelevel.ai
    name: strimzi-kafka-operator
    tag: v0.50.1
userOperator:
  image:
    registry: cgr.dev
    repository: eyelevel.ai
    name: strimzi-kafka-operator
    tag: v0.50.1
kafkaInit:
  image:
    registry: cgr.dev
    repository: eyelevel.ai
    name: strimzi-kafka-operator
    tag: v0.50.1
kafkaExporter:
  image:
    registry: cgr.dev
    repository: eyelevel.ai
    name: strimzi-kafka
    tagPrefix: v0.50.1
kafkaMirrorMaker2:
  image:
    registry: cgr.dev
    repository: eyelevel.ai
    name: strimzi-kafka
    tagPrefix: v0.50.1
cruiseControl:
  image:
    registry: cgr.dev
    repository: eyelevel.ai
    name: strimzi-kafka
    tagPrefix: v0.50.1
