{{- $extract := .Values.extract | default dict -}}
{{- $api := dig "api" dict $extract -}}
{{- $budget := dig "disruptionBudget" dict $api -}}
{{- if and (eq (include "groundx.extract.api.create" .) "true") (dig "enabled" false $budget) }}
{{- $name := include "groundx.extract.api.serviceName" . }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $name }}
  namespace: {{ include "groundx.ns" . | quote }}
  labels:
{{ include "groundx.renderDefaultLabels" (dict "name" $name "indent" 4 "root" .) }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ $name }}
{{- end }}
