{{- if gt (int .Values.cluster.replicas) (int .Values.nodepool.replicas) -}}
{{ fail (printf "cluster.replicas (%d) must not exceed nodepool.replicas (%d)" (int .Values.cluster.replicas) (int .Values.nodepool.replicas)) }}
{{- end -}}
apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: {{ .Values.serviceName }}-cluster
  namespace: {{ .Release.Namespace }}
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    {{- with .Values.cluster.version }}
    version: {{ . }}
    {{- end }}
    {{- with .Values.cluster.metaVersion }}
    metadataVersion: {{ . | quote }}
    {{- end }}
    listeners:
      - name: kafka
        port: {{ .Values.cluster.port }}
        type: internal
        tls: false
    config:
      default.replication.factor: {{ .Values.cluster.replicas }}
      offsets.topic.replication.factor: {{ .Values.cluster.replicas }}
      transaction.state.log.replication.factor: {{ .Values.cluster.replicas }}
      transaction.state.log.min.isr: {{ .Values.cluster.replicas }}
      min.insync.replicas: {{ .Values.cluster.replicas }}
      group.initial.rebalance.delay.ms: 0
      auto.create.topics.enable: true
      unstable.api.versions.enable: "true"
      unstable.feature.versions.enable: "true"
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: node
                    operator: In
                    values:
                    - "{{ .Values.node }}"
        tolerations:
          - key: "node"
            value: "{{ .Values.node }}"
            effect: "NoSchedule"
  entityOperator:
    topicOperator: {}
    userOperator: {}
