apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: {{ .Values.serviceName }}-dual-role
  namespace: {{ .Values.namespace }}
  labels:
    strimzi.io/cluster: {{ .Values.serviceName }}-cluster
spec:
  replicas: {{ .Values.nodepool.replicas }}
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: {{ .Values.nodepool.storage }}
        deleteClaim: true
        kraftMetadata: shared
