{{- $svcs := (include "groundx.golang.services" . | fromYaml) -}}

{{- range $idx, $entry := $svcs }}
{{- $svcKey := printf "groundx.%s.settings" $entry -}}
{{- $svcData := include $svcKey $ | fromYaml -}}

{{- $cport := get $svcData "port" -}}
{{- $dpnd := get $svcData "dependencies" | default dict -}}
{{- $image := get $svcData "image" -}}
{{- $lb := get $svcData "loadBalancer" -}}
{{- $replicas := get $svcData "replicas" -}}
{{- $res := get $svcData "resources" -}}
{{- $pull := get $svcData "pull" -}}
{{- $sctx := get $svcData "securityContext" -}}
{{- $svc := get $svcData "name" -}}

{{- $desired := get $replicas "desired" -}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $svc }}
  namespace: {{ include "groundx.ns" $ | quote }}
  labels:
{{ include "groundx.renderDefaultLabels" (dict "name" $svc "indent" 4 "root" $) }}
spec:
  replicas: {{ $desired }}
  selector:
    matchLabels:
      app: {{ $svc }}
  template:
    metadata:
      labels:
        app: {{ $svc }}
    spec:
{{ include "groundx.renderSecurityContext" (dict "ctx" $sctx "indent" 6 "root" $ "user" 1001) }}
{{ include "groundx.renderNodeSelector" (dict "name" $svc "indent" 6 "root" $) }}
{{- if not (empty $dpnd) }}
      initContainers:
{{- if hasKey $dpnd "groundx" }}
        - name: wait-for-groundx
          image: {{ include "groundx.busybox.image" $ }}
          imagePullPolicy: {{ include "groundx.busybox.pull" $ | quote }}
          command: ['sh', '-c', "until wget --spider -q {{ include "groundx.groundx.serviceUrl" $ }}/health; do echo waiting for groundx; sleep 2; done"]
{{- end }}
{{- if hasKey $dpnd "cache" }}
        - name: wait-for-cache
          image: {{ include "groundx.busybox.image" $ }}
          imagePullPolicy: {{ include "groundx.busybox.pull" $ | quote }}
          command: ['sh', '-c', "until nc -z {{ printf "%s %v" (include "groundx.cache.addr" $) (include "groundx.cache.port" $) }}; do echo waiting for cache; sleep 2; done"]
{{- end }}
{{- if hasKey $dpnd "file" }}
        - name: wait-for-file-storage
          image: {{ include "groundx.busybox.image" $ }}
          imagePullPolicy: {{ include "groundx.busybox.pull" $ | quote }}
          command: ['sh', '-c', "until nc -z {{ printf "%s %v" (include "groundx.file.serviceDependency" $) (include "groundx.file.port" $) }}; do echo waiting for file storage; sleep 2; done"]
{{- end }}
{{- if and (not $.Values.ingestOnly) (hasKey $dpnd "search") }}
        - name: wait-for-search
          image: {{ include "groundx.busybox.image" $ }}
          imagePullPolicy: {{ include "groundx.busybox.pull" $ | quote }}
          command: ['sh', '-c', "until nc -z {{ printf "%s %v" (include "groundx.search.baseDomain" $) (include "groundx.search.port" $) }}; do echo waiting for search; sleep 2; done"]
{{- end }}
{{- if hasKey $dpnd "db" }}
        - name: wait-for-database
          image: {{ include "groundx.busybox.image" $ }}
          imagePullPolicy: {{ include "groundx.busybox.pull" $ | quote }}
          command: ['sh', '-c', "until nc -z {{ printf "%s %v" (include "groundx.db.ro" $) (include "groundx.db.port" $) }}; do echo waiting for database; sleep 2; done"]
{{- end }}
{{- if hasKey $dpnd "stream" }}
        - name: wait-for-stream
          image: {{ include "groundx.busybox.image" $ }}
          imagePullPolicy: {{ include "groundx.busybox.pull" $ | quote }}
          command: ['sh', '-c', "until nc -z {{ printf "%s %v" (include "groundx.stream.domain" $) (include "groundx.stream.port" $) }}; do echo waiting for stream; sleep 2; done"]
{{- end }}
{{- end }}
      containers:
        - name: {{ $svc }}
          image: {{ $image | quote }}
          imagePullPolicy: {{ $pull | quote }}
          ports:
            - containerPort: {{ $cport }}
              protocol: TCP
{{ include "groundx.renderSecurityContext" (dict "ctx" $sctx "indent" 10 "root" $ "user" 1001) }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ $cport }}
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: {{ $cport }}
            initialDelaySeconds: 10
            periodSeconds: 30
{{- if $res }}
{{ include "groundx.renderContainerResources" (dict "ctx" $res "indent" 10) }}
{{- end }}
          volumeMounts:
            - name: config-volume
              mountPath: /home/{{ include "groundx.golang.username" $ }}/.cashbot/config.yaml
              subPath: config.yaml
            - name: init-db-volume
              mountPath: /app/init-db.sql
              subPath: init-db.sql
      volumes:
        - name: config-volume
          configMap:
            name: config-yaml-map
        - name: init-db-volume
          configMap:
            name: init-database-file
{{- if $lb }}
{{- if eq $.Values.cluster.type "openshift" }}
{{ include "groundx.renderRoute" (dict "name" $svc "lb" $lb "root" $) }}
{{- else }}
{{ include "groundx.renderLoadBalancer" (dict "name" $svc "lb" $lb "root" $) }}
{{- end }}
{{- end }}

{{ end }}
