{{- $svcs := (include "groundx.api.services" . | fromYaml) -}}

{{- range $idx, $entry := $svcs }}
{{- $svcKey := printf "groundx.%s.settings" $entry -}}
{{- $svcData := include $svcKey $ | fromYaml -}}

{{- $cport := get $svcData "port" -}}
{{- $image := get $svcData "image" -}}
{{- $lb := get $svcData "loadBalancer" -}}
{{- $replicas := get $svcData "replicas" -}}
{{- $res := get $svcData "resources" -}}
{{- $pull := get $svcData "pull" -}}
{{- $sctx := get $svcData "securityContext" -}}
{{- $svc := get $svcData "name" -}}

{{- $desired := get $replicas "desired" -}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $svc }}
  namespace: {{ include "groundx.ns" $ | quote }}
  labels:
{{ include "groundx.renderDefaultLabels" (dict "name" $svc "indent" 4 "root" $) }}
spec:
  replicas: {{ $desired }}
  selector:
    matchLabels:
      app: {{ $svc }}
  template:
    metadata:
      labels:
        app: {{ $svc }}
    spec:
{{ include "groundx.renderSecurityContext" (dict "ctx" $sctx "indent" 6 "root" $ "user" 1001) }}
{{ include "groundx.renderNodeSelector" (dict "name" $svc "indent" 6 "root" $) }}
      initContainers:
        - name: wait-for-cache
          image: {{ include "groundx.busybox.image" $ }}
          imagePullPolicy: {{ include "groundx.busybox.pull" $ | quote }}
          command: ['sh', '-c', "until nc -z {{ printf "%s %v" (include "groundx.cache.addr" $) (include "groundx.cache.port" $) }}; do echo waiting for cache; sleep 2; done"]
      containers:
        - name: {{ $svc }}
          image: {{ $image | quote }}
          imagePullPolicy: {{ $pull | quote }}
          ports:
            - containerPort: {{ $cport }}
              protocol: TCP
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          workingDir: /app
          command:
            - /bin/bash
            - -c
            - |
              export PYTHONPATH=/app && LOCAL=0 gunicorn -c /app/gunicorn_conf.py --capture-output --enable-stdio-inheritance
{{ include "groundx.renderSecurityContext" (dict "ctx" $sctx "indent" 10 "root" $ "user" 1001) }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ $cport }}
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: {{ $cport }}
            initialDelaySeconds: 10
            periodSeconds: 30
{{- if $res }}
{{ include "groundx.renderContainerResources" (dict "ctx" $res "indent" 10) }}
{{- end }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.py
              subPath: config.py
            - name: gunicorn-conf-volume
              mountPath: /app/gunicorn_conf.py
              subPath: gunicorn_conf.py
      volumes:
        - name: config-volume
          configMap:
            name: layout-config-py-map
        - name: gunicorn-conf-volume
          configMap:
            name: layout-gunicorn-conf-py-map

{{ end }}
