{{- $svcs := (include "groundx.layout.process.services" . | fromYaml) -}}

{{- range $idx, $entry := $svcs }}
{{- $svcKey := printf "groundx.%s.settings" $entry -}}
{{- $svcData := include $svcKey $ | fromYaml -}}

{{- $image := get $svcData "image" -}}
{{- $replicas := get $svcData "replicas" -}}
{{- $res := get $svcData "resources" -}}
{{- $pull := get $svcData "pull" -}}
{{- $sctx := get $svcData "securityContext" -}}
{{- $svc := get $svcData "name" -}}

{{- $desired := get $replicas "desired" -}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $svc }}
  namespace: {{ include "groundx.ns" $ | quote }}
  labels:
{{ include "groundx.renderDefaultLabels" (dict "name" $svc "indent" 4 "root" $) }}
spec:
  replicas: {{ $desired }}
  selector:
    matchLabels:
      app: {{ $svc }}
  template:
    metadata:
      labels:
        app: {{ $svc }}
    spec:
{{ include "groundx.renderSecurityContext" (dict "ctx" $sctx "indent" 6 "root" $ "user" 1001) }}
{{ include "groundx.renderNodeSelector" (dict "name" $svc "indent" 6 "root" $) }}
      initContainers:
        - name: wait-for-cache
          image: {{ include "groundx.busybox.image" $ }}
          imagePullPolicy: {{ include "groundx.busybox.pull" $ | quote }}
          command: ['sh', '-c', "until nc -z {{ printf "%s %v" (include "groundx.cache.addr" $) (include "groundx.cache.port" $) }}; do echo waiting for cache; sleep 2; done"]
        - name: wait-for-file-storage
          image: {{ include "groundx.busybox.image" $ }}
          imagePullPolicy: {{ include "groundx.busybox.pull" $ | quote }}
          command: ['sh', '-c', "until nc -z {{ printf "%s %v" (include "groundx.file.serviceDependency" $) (include "groundx.file.port" $) }}; do echo waiting for file storage; sleep 2; done"]
      containers:
        - name: {{ $svc }}
          image: {{ $image | quote }}
          imagePullPolicy: {{ $pull | quote }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          workingDir: /app
          command:
            - /bin/sh
            - -c
            - |
              export PYTHONPATH=/app && supervisord -c /app/supervisord.conf
{{ include "groundx.renderSecurityContext" (dict "ctx" $sctx "indent" 10 "root" $ "user" 1001) }}
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - ps aux | grep 'document.celery_process.app' | grep -v grep || exit 1
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - ps aux | grep 'document.celery_process.app' | grep -v grep || exit 1
            initialDelaySeconds: 10
            periodSeconds: 30
{{- if $res }}
{{ include "groundx.renderContainerResources" (dict "ctx" $res "indent" 10) }}
{{- end }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.py
              subPath: config.py
            - name: credentials-volume
              mountPath: /app/credentials.json
              subPath: credentials.json
            - name: supervisord-volume
              mountPath: /app/supervisord.conf
              subPath: supervisord.conf
      volumes:
        - name: config-volume
          configMap:
            name: layout-config-py-map
        - name: credentials-volume
          configMap:
            name: layout-ocr-credentials-map
        - name: supervisord-volume
          configMap:
            name: {{ $svc }}-supervisord-conf-map

{{ end }}
