{{- if eq (include "groundx.cache.confEnabled" . | trim) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "groundx.cache.confSecretName" . | quote }}
  namespace: {{ include "groundx.ns" . | quote }}
  labels:
{{ include "groundx.renderDefaultLabels" (dict "name" (include "groundx.cache.serviceName" .) "indent" 4 "root" $) }}
stringData:
  redis.conf: |
    {{ include "groundx.cache.confContent" . | nindent 4 }}
{{- end }}
