{{- $sups := (include "groundx.hpa" . | fromYaml | default dict) -}}
{{- $ns := include "groundx.ns" . -}}
{{- range $n, $entry := $sups }}
{{- $svcKey := printf "groundx.%s.hpa" $entry -}}
{{- $svcData := include $svcKey $ | fromYaml -}}

{{- if gt (len $svcData) 0 }}

{{- $anns := dig "annotations" dict $svcData -}}
{{- $downCooldown := dig "downCooldown" "" $svcData -}}
{{- $lbls := dig "labels" dict $svcData -}}
{{- $metric := dig "metric" "" $svcData -}}
{{- $podName := dig "name" "" $svcData -}}
{{- $hpaName := printf "%s-hpa" $podName -}}
{{- $replicas := dig "replicas" dict $svcData -}}
{{- $upCooldown := dig "upCooldown" "" $svcData -}}

{{- $max := dig "max" "1" $replicas -}}
{{- $min := dig "min" "1" $replicas -}}
{{- $target := dig "target" "0.8" $replicas -}}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $hpaName }}
  namespace: {{ $ns }}
  labels:
    app: {{ $hpaName }}
{{- include "groundx.renderDefaultLabels" (dict "indent" 4 "root" $) }}
{{- if gt (len $lbls) 0 }}
{{- toYaml $lbls | nindent 4 }}
{{- end }}
{{- if gt (len $anns) 0 }}
  annotations:
{{- toYaml $anns | nindent 4 }}
{{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $podName }}
  minReplicas: {{ $min }}
  maxReplicas: {{ $max }}
  metrics:
    - type: External
      external:
        metric:
          name: {{ $metric }}
        target:
          type: Value
          value: {{ $target }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ $upCooldown }}
      policies:
        - type: Percent
          value: 100
          periodSeconds: {{ $upCooldown }}
        - type: Pods
          value: 4
          periodSeconds: {{ $upCooldown }}
    scaleDown:
      stabilizationWindowSeconds: {{ $downCooldown }}
      policies:
        - type: Percent
          value: 50
          periodSeconds: {{ $downCooldown }}
        - type: Pods
          value: 2
          periodSeconds: {{ $downCooldown }}

{{ end }}

{{ end }}
