{{- $sups := (include "groundx.layout.supervisor" . | fromYaml) -}}
{{- $ns := include "groundx.ns" . -}}
{{- $svc := include "groundx.layout.serviceName" . -}}
{{- range $n, $entry := $sups }}
{{- $svcKey := printf "groundx.%s.settings" $entry -}}
{{- $svcData := include $svcKey $ | fromYaml -}}

{{- $name := get $svcData "name" -}}
{{- $queue := get $svcData "queue" -}}
{{- $threads := get $svcData "threads" -}}
{{- $workers := int (get $svcData "workers") -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}-supervisord-conf-map
  namespace: {{ $ns }}
  labels:
{{ include "groundx.renderDefaultLabels" (dict "name" "" "indent" 4 "root" $) }}
data:
  supervisord.conf: |
    [supervisord]
    nodaemon=true
    logfile=/dev/null
    {{ printf "" }}

    {{- range $i, $_ := until $workers }}
    [program:celery_worker_{{ add $i 1 }}]
    command=celery -A document.celery_process.app worker -n %(ENV_POD_NAME)s-w{{ add $i 1 }} --loglevel={{ include "groundx.logLevel" $ | upper }} --queues={{ join "," $queue }} --concurrency={{ $threads }} {{include "groundx.celery.options" $}}
    environment=
      {{- if contains "inference" $name }}
      CELERY_WORKER_NAME="%(ENV_POD_NAME)s-w{{ add $i 1 }}",
      {{- end }}
      LOCAL="0",
      PYTHONUNBUFFERED="1"{{include "groundx.celery.env" $}}
    autostart=true
    autorestart=true
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0
    {{ end }}

    {{- if contains "inference" $name }}
    [program:celery_monitor]
    command=python /app/document_monitor.py
    environment=
      LOCAL="0",
      PYTHONUNBUFFERED="1"
    autostart=true
    autorestart=true
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0

    [program:celery_health]
    command=python /app/document_health.py
    environment=
      LOCAL="0",
      PYTHONUNBUFFERED="1"
    autostart=true
    autorestart=true
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0
    {{- end }}

{{ end }}
