{{- $sups := (include "groundx.secrets" . | fromYaml | default dict) -}}
{{- $ns := include "groundx.ns" . -}}
{{- range $n, $entry := $sups }}
{{- $svcKey := printf "groundx.%s.secrets" $entry -}}
{{- $svcData := include $svcKey $ | fromYaml -}}

{{- $name := get $svcData "name" -}}
{{- $data := get $svcData "data" -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ $ns }}
type: Opaque
data:
  {{- range $key, $val := $data }}
    {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}

{{ end }}
