{{- $ic := include "groundx.summary.api.create" . -}}

{{- if eq $ic "true" }}
{{- $svc := include "groundx.summary.serviceName" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $svc }}-gunicorn-conf-py-map
  namespace: {{ include "groundx.ns" . }}
  labels:
{{ include "groundx.renderDefaultLabels" (dict "name" "" "indent" 4 "root" $) }}
data:
  gunicorn_conf.py: |
    infolog = "-"
    accesslog = "-"
    errorlog = "-"

    loglevel = {{ include "groundx.logLevel" . | quote }}
    workers = {{ include "groundx.summary.api.workers" . }}
    threads = {{ include "groundx.summary.api.threads" . }}
    timeout = {{ include "groundx.summary.api.timeout" . }}
    timeout_keep_alive = 15

    worker_class = "uvicorn.workers.UvicornWorker"

    bind = "0.0.0.0:{{ include "groundx.summary.api.containerPort" . }}"

    wsgi_app = "summary_server:app"
{{- end }}
