{{- $cc := include "groundx.cache.create" . -}}
{{- if ne $cc "false" -}}
{{- $svc := include "groundx.cache.serviceName" . -}}
{{- $lb := include "groundx.cache.loadBalancer" . -}}
{{- $mountName := printf "%s-persistent-storage" $svc -}}
{{- $cport := include "groundx.cache.containerPort" . -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $svc | quote }}
  namespace: {{ include "groundx.ns" . | quote }}
  labels:
{{ include "groundx.renderDefaultLabels" (dict "name" $svc "indent" 4 "root" $) }}
spec:
  serviceName: {{ $svc | quote }}
  replicas: {{ .Values.cache.replicas.desired }}
  selector:
    matchLabels:
      app: {{ $svc | quote }}
  template:
    metadata:
      labels:
        app: {{ $svc | quote }}
    spec:
{{ include "groundx.renderSecurityContext" (dict "ctx" .Values.cache.securityContext "indent" 6 "root" $ "user" 1001 "simple" "true") }}
{{ include "groundx.renderNodeSelector" (dict "name" $svc "indent" 6 "root" $) }}
      containers:
        - name: {{ $svc | quote }}
          image: {{ include "groundx.cache.image" . | quote }}
          imagePullPolicy: {{ include "groundx.cache.imagePullPolicy" . | quote }}
          ports:
            - containerPort: {{ $cport}}
              protocol: TCP
{{ include "groundx.renderSecurityContext" (dict "ctx" .Values.cache.securityContext "indent" 10 "root" $ "user" 1001 "simple" "true") }}
{{- with .Values.cache.resources }}
{{ include "groundx.renderContainerResources" (dict "ctx" . "indent" 10) }}
{{- end }}
          volumeMounts:
            - name: {{ $mountName | quote }}
              mountPath: {{ include "groundx.cache.mountPath" . | quote }}
      volumes:
        - name: {{ $mountName | quote }}
          emptyDir: {}
{{- if $lb }}
{{- if eq .Values.cluster.type "openshift" }}
{{ include "groundx.renderRoute" (dict "name" $svc "lb" $lb "root" $) }}
{{- else }}
{{ include "groundx.renderLoadBalancer" (dict "name" $svc "lb" $lb "root" $) }}
{{- end }}
{{- end }}

{{- end }}
