{{- $cc := include "groundx.cache.create" . -}}
{{- if ne $cc "false" -}}
{{- $in := .Values.cache | default dict -}}
{{- $svc := include "groundx.cache.serviceName" . -}}
{{- $username := include "groundx.container.username" . -}}

{{- $cport := include "groundx.cache.containerPort" . -}}
{{- $int := include "groundx.cache.interface" . -}}
{{- $mountName := printf "%s-persistent-storage" $svc -}}
{{- $node := include "groundx.cache.node" . -}}
{{- $rp := include "groundx.cache.replicas" . | fromYaml -}}

{{- $aff := dig "affinity" dict $in -}}
{{- $anns := dig "annotations" dict $in -}}
{{- $csct := dig "containerSecurityContext" dict $in -}}
{{- $ips := include "groundx.imagePullSecrets" . | fromYaml -}}
{{- $lbls := dig "labels" dict $in -}}
{{- $nsl := dig "nodeSelector" dict $in -}}
{{- $rs := dig "resources" dict $in -}}
{{- $sct := dig "securityContext" dict $in -}}
{{- $san := include "groundx.cache.serviceAccountName" . -}}
{{- $tl := dig "tolerations" list $in -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $svc | quote }}
  namespace: {{ include "groundx.ns" . | quote }}
  labels:
{{ include "groundx.renderDefaultLabels" (dict "name" $svc "indent" 4 "root" $) }}
spec:
  serviceName: {{ $svc | quote }}
  replicas: {{ dig "desired" 1 $rp }}
  selector:
    matchLabels:
      app: {{ $svc | quote }}
  template:
    metadata:
      labels:
        app: {{ $svc | quote }}
{{- if gt (len $lbls) 0 }}
{{ toYaml $lbls | nindent 8 }}
{{- end }}
{{- if gt (len $anns) 0 }}
      annotations:
{{ toYaml $anns | nindent 8 }}
{{- end }}
    spec:
{{- if and ($san) (ne $san "") }}
      serviceAccountName: {{ $san }}
{{- end }}
{{- if gt (len $ips) 0 }}
      imagePullSecrets:
{{- range $j, $inm := $ips }}
        - name: {{ $inm }}
{{- end }}
{{- end }}
{{- if gt (len $aff) 0 }}
      affinity:
{{ toYaml $aff | nindent 8 }}
{{- end }}
{{ include "groundx.renderSecurityContext" (dict "ctx" $sct "indent" 6 "root" $ "user" $username "cfg" "spec") }}
{{- include "groundx.renderNodeSelector" (dict "ctx" $nsl "node" $node "indent" 6 "root" $) }}
{{- include "groundx.renderTolerations" (dict "ctx" $tl "node" $node "indent" 6 "root" $) }}
      containers:
        - name: {{ $svc | quote }}
          image: {{ include "groundx.cache.image" . | quote }}
          imagePullPolicy: {{ include "groundx.cache.imagePullPolicy" . | quote }}
          ports:
            - containerPort: {{ $cport}}
              protocol: TCP
{{ include "groundx.renderSecurityContext" (dict "ctx" $csct "indent" 10 "root" $ "user" $username "cfg" "container") }}
{{ include "groundx.renderContainerResources" (dict "ctx" $rs "indent" 10) }}
          volumeMounts:
            - name: {{ $mountName | quote }}
              mountPath: {{ include "groundx.cache.mountPath" . | quote }}
      volumes:
        - name: {{ $mountName | quote }}
          emptyDir: {}

{{ include "groundx.renderInterface" (dict "name" $svc "lb" $int "root" $) }}

{{- end }}
