apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.service.name }}
spec:
  capacity:
    storage: {{ .Values.capacity }}
  accessModes:
    - {{ .Values.access }}
  persistentVolumeReclaimPolicy: Delete
  storageClassName: {{ .Values.storage }}
  hostPath:
    path: {{ .Values.mount }}