namespace: eyelevel

cluster:
  pvClass: eyelevel-pv
  type: aks

cache:
  affinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - myapp
        topologyKey: "kubernetes.io/hostname"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
  containerPort: 8081
  containerSecurityContext:
    readOnlyRootFilesystem: true
  image: test.image:v1
  imagePullPolicy: Never
  labels:
    app.kubernetes.io/name: myapp
    app.kubernetes.io/component: backend
  loadBalancer:
    ipType: LoadBalancer
    isInternal: true
    port: 6377
    ssl: true
    timeout: 30
  mountPath: /ok/here
  node: ""
  nodeSelector:
    disktype: ssd
    kubernetes.io/os: linux
  port: 8082
  securityContext:
    fsGroup: 2000
  serviceName: myapp

  metrics:
    affinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - myapp
          topologyKey: "kubernetes.io/hostname"
    annotations:
      prometheus.io/port: "8081"
    containerPort: 8081
    containerSecurityContext:
      readOnlyRootFilesystem: true
    image: test.image:v1
    imagePullPolicy: Never
    labels:
      app.kubernetes.io/name: myapp
    loadBalancer:
      ipType: Route
      isInternal: true
      port: 6377
      ssl: true
      timeout: 30
    mountPath: /ok/here
    node: ""
    port: 8082
    securityContext:
      fsGroup: 2000
    serviceName: myapp
    tolerations:
      - effect: "NoSchedule"
        key: "workload-type"
        operator: "Equal"
        value: "batch"

summary:
  defaultKitId: 1
  serviceName: myapp

  api:
    affinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - myapp
          topologyKey: "kubernetes.io/hostname"
    annotations:
      prometheus.io/port: "8081"
    containerPort: 8081
    containerSecurityContext:
      readOnlyRootFilesystem: true
    image: test.image:v1
    imagePullPolicy: Never
    labels:
      app.kubernetes.io/name: myapp
    loadBalancer:
      ipType: LoadBalancer
      isInternal: true
      port: 6377
      ssl: true
      timeout: 30
    node: ""
    nodeSelector:
      disktype: ssd
    securityContext:
      fsGroup: 2000
    threads: 2
    timeout: 5
    workers: 4
  inference:
    affinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - myapp
          topologyKey: "kubernetes.io/hostname"
    annotations:
      prometheus.io/port: "8081"
    containerPort: 8081
    containerSecurityContext:
      readOnlyRootFilesystem: true
    deviceType: cpu
    deviceUtilize: 0.37
    image: test.image:v1
    imagePullPolicy: Never
    labels:
      app.kubernetes.io/name: myapp
    node: test-label-1
    nodeSelector:
      disktype: ssd
    pvc:
      access: ReadOnce
      capacity: 1Gi
      class: test-pv
      name: test-pvc
    queue: my-queue
    securityContext:
      fsGroup: 2000
    threads: 2
    tolerations:
      - effect: "NoSchedule"
        key: "workload-type"
        operator: "Equal"
        value: "batch"
    workers: 4

groundx:
  affinity:
    podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - myapp
        topologyKey: "kubernetes.io/hostname"
  annotations:
    prometheus.io/port: "8081"
  containerPort: 8081
  containerSecurityContext:
    readOnlyRootFilesystem: true
  image: test.image:v1
  imagePullPolicy: Never
  labels:
    app.kubernetes.io/name: myapp
  loadBalancer:
    ipType: LoadBalancer
    isInternal: true
    port: 6377
    ssl: true
    timeout: 30
  node: test-label-1
  nodeSelector:
    disktype: ssd
  securityContext:
    fsGroup: 2000
  serviceName: myapp
  tolerations:
    - effect: "NoSchedule"
      key: "workload-type"
      operator: "Equal"
      value: "batch"

layout:
  serviceName: myapp

  correct:
    affinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - myapp
          topologyKey: "kubernetes.io/hostname"
    annotations:
      prometheus.io/port: "8081"
    containerPort: 8081
    containerSecurityContext:
      readOnlyRootFilesystem: true
    image: test.image:v1
    imagePullPolicy: Never
    labels:
      app.kubernetes.io/name: myapp
    node: test-label-1
    nodeSelector:
      disktype: ssd
    queue: my-queue
    securityContext:
      fsGroup: 2000
    threads: 2
    tolerations:
      - effect: "NoSchedule"
        key: "workload-type"
        operator: "Equal"
        value: "batch"
    workers: 4

  inference:
    affinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - myapp
          topologyKey: "kubernetes.io/hostname"
    annotations:
      prometheus.io/port: "8081"
    containerPort: 8081
    containerSecurityContext:
      readOnlyRootFilesystem: true
    deviceType: cpu
    image: test.image:v1
    imagePullPolicy: Never
    labels:
      app.kubernetes.io/name: myapp
    node: test-label-1
    nodeSelector:
      disktype: ssd
    queue: my-queue
    securityContext:
      fsGroup: 2000
    threads: 2
    tolerations:
      - effect: "NoSchedule"
        key: "workload-type"
        operator: "Equal"
        value: "batch"
    workers: 4

  map:
    affinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - myapp
          topologyKey: "kubernetes.io/hostname"
    annotations:
      prometheus.io/port: "8081"
    containerPort: 8081
    containerSecurityContext:
      readOnlyRootFilesystem: true
    image: test.image:v1
    imagePullPolicy: Never
    labels:
      app.kubernetes.io/name: myapp
    node: test-label-1
    nodeSelector:
      disktype: ssd
    queue: my-queue
    securityContext:
      fsGroup: 2000
    threads: 2
    tolerations:
      - effect: "NoSchedule"
        key: "workload-type"
        operator: "Equal"
        value: "batch"
    workers: 4

  ocr:
    affinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - myapp
          topologyKey: "kubernetes.io/hostname"
    annotations:
      prometheus.io/port: "8081"
    containerPort: 8081
    containerSecurityContext:
      readOnlyRootFilesystem: true
    image: test.image:v1
    imagePullPolicy: Never
    labels:
      app.kubernetes.io/name: myapp
    node: test-label-1
    nodeSelector:
      disktype: ssd
    project: test-project
    queue: my-queue
    securityContext:
      fsGroup: 2000
    threads: 2
    tolerations:
      - effect: "NoSchedule"
        key: "workload-type"
        operator: "Equal"
        value: "batch"
    type: google
    workers: 4

  process:
    affinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - myapp
          topologyKey: "kubernetes.io/hostname"
    annotations:
      prometheus.io/port: "8081"
    batchSize: 3
    containerPort: 8081
    containerSecurityContext:
      readOnlyRootFilesystem: true
    image: test.image:v1
    imagePullPolicy: Never
    labels:
      app.kubernetes.io/name: myapp
    node: test-label-1
    nodeSelector:
      disktype: ssd
    queue: my-queue
    securityContext:
      fsGroup: 2000
    threads: 2
    tolerations:
      - effect: "NoSchedule"
        key: "workload-type"
        operator: "Equal"
        value: "batch"
    workers: 4

  save:
    affinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - myapp
          topologyKey: "kubernetes.io/hostname"
    annotations:
      prometheus.io/port: "8081"
    containerPort: 8081
    containerSecurityContext:
      readOnlyRootFilesystem: true
    image: test.image:v1
    imagePullPolicy: Never
    labels:
      app.kubernetes.io/name: myapp
    node: test-label-1
    nodeSelector:
      disktype: ssd
    queue: my-queue
    securityContext:
      fsGroup: 2000
    threads: 2
    tolerations:
      - effect: "NoSchedule"
        key: "workload-type"
        operator: "Equal"
        value: "batch"
    workers: 4

layoutWebhook:
  affinity:
    podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - myapp
        topologyKey: "kubernetes.io/hostname"
  annotations:
    prometheus.io/port: "8081"
  containerPort: 8081
  containerSecurityContext:
    readOnlyRootFilesystem: true
  image: test.image:v1
  imagePullPolicy: Never
  labels:
    app.kubernetes.io/name: myapp
  loadBalancer:
    ipType: LoadBalancer
    isInternal: true
    port: 6377
    ssl: true
    timeout: 30
  node: test-label-1
  nodeSelector:
    disktype: ssd
  securityContext:
    fsGroup: 2000
  serviceName: myapp
  tolerations:
    - effect: "NoSchedule"
      key: "workload-type"
      operator: "Equal"
      value: "batch"

preProcess:
  affinity:
    podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - myapp
        topologyKey: "kubernetes.io/hostname"
  annotations:
    prometheus.io/port: "8081"
  containerPort: 8081
  containerSecurityContext:
    readOnlyRootFilesystem: true
  image: test.image:v1
  imagePullPolicy: Never
  labels:
    app.kubernetes.io/name: myapp
  node: test-label-1
  nodeSelector:
    disktype: ssd
  queueSize: 2
  securityContext:
    fsGroup: 2000
  serviceName: myapp
  tolerations:
    - effect: "NoSchedule"
      key: "workload-type"
      operator: "Equal"
      value: "batch"

process:
  affinity:
    podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - myapp
        topologyKey: "kubernetes.io/hostname"
  annotations:
    prometheus.io/port: "8081"
  containerPort: 8081
  containerSecurityContext:
    readOnlyRootFilesystem: true
  image: test.image:v1
  imagePullPolicy: Never
  labels:
    app.kubernetes.io/name: myapp
  node: test-label-1
  nodeSelector:
    disktype: ssd
  queueSize: 2
  securityContext:
    fsGroup: 2000
  serviceName: myapp
  tolerations:
    - effect: "NoSchedule"
      key: "workload-type"
      operator: "Equal"
      value: "batch"

queue:
  affinity:
    podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - myapp
        topologyKey: "kubernetes.io/hostname"
  annotations:
    prometheus.io/port: "8081"
  containerPort: 8081
  containerSecurityContext:
    readOnlyRootFilesystem: true
  image: test.image:v1
  imagePullPolicy: Never
  labels:
    app.kubernetes.io/name: myapp
  node: test-label-1
  nodeSelector:
    disktype: ssd
  queueSize: 2
  securityContext:
    fsGroup: 2000
  serviceName: myapp
  tolerations:
    - effect: "NoSchedule"
      key: "workload-type"
      operator: "Equal"
      value: "batch"

ranker:
  serviceName: myapp

  api:
    affinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - myapp
          topologyKey: "kubernetes.io/hostname"
    annotations:
      prometheus.io/port: "8081"
    containerPort: 8081
    containerSecurityContext:
      readOnlyRootFilesystem: true
    image: test.image:v1
    imagePullPolicy: Never
    labels:
      app.kubernetes.io/name: myapp
    loadBalancer:
      ipType: LoadBalancer
      isInternal: true
      port: 6377
      ssl: true
      timeout: 30
    node: ""
    securityContext:
      fsGroup: 2000
    threads: 2
    timeout: 30
    tolerations:
      - effect: "NoSchedule"
        key: "workload-type"
        operator: "Equal"
        value: "batch"
    workers: 4

  inference:
    affinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - myapp
          topologyKey: "kubernetes.io/hostname"
    annotations:
      prometheus.io/port: "8081"
    containerPort: 8081
    containerSecurityContext:
      readOnlyRootFilesystem: true
    deviceType: cpu
    image: test.image:v1
    imagePullPolicy: Never
    labels:
      app.kubernetes.io/name: myapp
    node: test-label-1
    nodeSelector:
      disktype: ssd
    pvc:
      access: ReadOnce
      capacity: 1Gi
      class: test-pv
      name: test-pvc
    queue: my-queue
    securityContext:
      fsGroup: 2000
    threads: 2
    tolerations:
      - effect: "NoSchedule"
        key: "workload-type"
        operator: "Equal"
        value: "batch"
    workers: 4

summaryClient:
  affinity:
    podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - myapp
        topologyKey: "kubernetes.io/hostname"
  annotations:
    prometheus.io/port: "8081"
  containerPort: 8081
  containerSecurityContext:
    readOnlyRootFilesystem: true
  image: test.image:v1
  imagePullPolicy: Never
  labels:
    app.kubernetes.io/name: myapp
  node: test-label-1
  nodeSelector:
    disktype: ssd
  queueSize: 5
  securityContext:
    fsGroup: 2000
  serviceName: myapp
  tolerations:
    - effect: "NoSchedule"
      key: "workload-type"
      operator: "Equal"
      value: "batch"

upload:
  affinity:
    podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - myapp
        topologyKey: "kubernetes.io/hostname"
  annotations:
    prometheus.io/port: "8081"
  containerPort: 8081
  containerSecurityContext:
    readOnlyRootFilesystem: true
  image: test.image:v1
  imagePullPolicy: Never
  labels:
    app.kubernetes.io/name: myapp
  node: test-label-1
  nodeSelector:
    disktype: ssd
  queueSize: 2
  securityContext:
    fsGroup: 2000
  serviceName: myapp
  tolerations:
    - effect: "NoSchedule"
      key: "workload-type"
      operator: "Equal"
      value: "batch"
