namespace: eyelevel
pvClass: eyelevel-pv

admin:
  apiKey: "00000000-0000-0000-0000-000000000000"
  email: "support@mycorp.net"
  password: "password"
  username: "00000000-0000-0000-0000-000000000000"

cluster:
  type: eks

  nodeLabels:
    cpuMemory: eyelevel-cpu-memory
    cpuOnly: eyelevel-cpu-only
    gpuLayout: eyelevel-gpu-layout
    gpuRanker: eyelevel-gpu-ranker
    gpuSummary: eyelevel-gpu-summary

  tls:
    existingSecret: ""

cache:
  enabled: true

  replicas:
    desired: 1
  isCluster: false

  resources:
    requests:
      cpu: "0.2"
      memory: 512Mi

  # set to use external cache
  # will supercede all other settings except metrics
  existing: {}
    # addr: redis.mycorp.net
    # isCluster: true
    # port: 6379

  metrics:
    # set false if you want to share 1 redis cache
    # for metrics and process metadata caching
    enabled: true

    replicas:
      desired: 1
    isCluster: false

    resources:
      requests:
        cpu: "0.2"
        memory: 512Mi

    # set to use external metrics cache
    # will supercede all other settings in metrics
    existing: {}
      # addr: redis-metrics.mycorp.net
      # isCluster: true
      # port: 6379

db:
  enabled: true

  dbName: eyelevel
  serviceUsername: eyelevel
  servicePassword: password

  # used to initialize DB
  # creates service user, db, and tables
  privilegedUsername: root
  privilegedPassword: password

  # set to use external MySQL DB
  existing: {}
#    ro: myro.mycorp.net
#    rw: myrw.mycorp.net
#    port: 3306

file:
  enabled: true

  bucketName: eyelevel
  username: minio
  password: minio123

  # minio or sqs
  serviceType: minio

  # set to use a custom domain for file URLs
  customDomain: ""

  # set to expose minio externally
  # in openshift, creates a route
  loadBalancer: {}
    # port: 8080

  # set to use existing minio file storage
  existing: {}
    # domain: minio.mycorp.net
    # port: 9000
    # ssl: true

search:
  enabled: true

  indexName: prod-1
  username: eyelevel
  password: R0otb_*t!kazs
  privilegedPassword: R0otb_*t!kazs
  privilegedUsername: admin

  # set to use existing opensearch
  existing: {}
    # domain: search.mycorp.net
    # url: https://search.mycorp.net:9200
    # port: 9200

stream:
  enabled: true

  replicas: 1
  storage: 10Gi

  serviceType: kafka

  nodepool:
    replicas: 1
    storage: 5Gi

  resources:
    requests:
      cpu: 200m
      memory: 512Mi

  existing: {}
#    domain: kafka.mycorp.net
#    port: 9092

summary:
  api:
    enabled: true

    replicas:
      desired: 1
  inference:
    enabled: true

    replicas:
      desired: 1

  existing: {}
#    apiKey: my-oai-key
#    serviceType: openai
#    url: https://api.openai.com/v1

groundx:
  enabled: true

  replicas:
    desired: 1

  resources:
    requests:
      cpu: 100m
      memory: 128Mi

layout:
  api:
    enabled: true

    replicas:
      desired: 1
  correct:
    enabled: true

    replicas:
      desired: 1
  inference:
    enabled: true

    replicas:
      desired: 1
  map:
    enabled: true

    replicas:
      desired: 1
  ocr:
    enabled: true

    replicas:
      desired: 1
  process:
    enabled: true

    replicas:
      desired: 1
  save:
    enabled: true

    replicas:
      desired: 1

layoutWebhook:
  enabled: true

  replicas:
    desired: 1

  resources:
    requests:
      cpu: 100m
      memory: 128Mi

preProcess:
  enabled: true

  replicas:
    desired: 1

  resources:
    requests:
      cpu: 200m
      memory: 1Gi

process:
  enabled: true

  replicas:
    desired: 1

  resources:
    requests:
      cpu: 200m
      memory: 256Mi

queue:
  enabled: true

  replicas:
    desired: 1

  resources:
    requests:
      cpu: 100m
      memory: 128Mi

ranker:
  api:
    enabled: true

    replicas:
      desired: 1
  inference:
    enabled: true

    replicas:
      desired: 1

summaryClient:
  enabled: true

  engines:
    - engineID: google/gemma-3-12b-it
      maxInputTokens: 100000
      maxOutputTokens: 2000
      maxRequests: 4
      requestLimit: 4
      vision: true

  replicas:
    desired: 1

  resources:
    requests:
      cpu: 100m
      memory: 512Mi

upload:
  enabled: true

  replicas:
    desired: 1

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
