nameOverride: db-cluster

backup:
  enabled: false
  nodeSelector:
    node: eyelevel-cpu-only

haproxy:
  enabled: true
  nodeSelector:
    node: eyelevel-cpu-only
  resources:
    requests:
      cpu: 600m
      memory: 1Gi
  size: 1

logcollector:
  enabled: false
  nodeSelector:
    node: eyelevel-cpu-only

nodeSelector:
  node: eyelevel-cpu-only

pmm:
  enabled: false
  nodeSelector:
    node: eyelevel-cpu-only

proxysql:
  enabled: false
  nodeSelector:
    node: eyelevel-cpu-only

pxc:
  nodeSelector:
    node: eyelevel-cpu-only
  persistence:
    size: 20Gi
  resources:
    requests:
      cpu: 600m
      memory: 512Mi
  size: 1

secrets:
  passwords:
    root: password
    xtrabackup: password
    monitor: password
    clustercheck: password
    proxyadmin: password
    operator: password
    replication: password
  # tls:
  #  cluster: eyelevel-cert
  #  internal: eyelevel-cert

unsafeFlags:
  pxcSize: true
  proxySize: true
