groundxKey: "00000000-0000-0000-0000-000000000000"

admin:
  apiKey: "00000000-0000-0000-0000-000000000000"
  email: "support@mycorp.net"
  password: "password"
  username: "00000000-0000-0000-0000-000000000000"

cluster:
  pvClass: eyelevel-pv
  type: eks

engines:
  default:
    engineId: gpt-5-mini
    reasoningEffort: low
    vision: true

summary:
  existing:
    apiKey: openai-api-key

    # openai, openai-base64 (base 64 encodes image data and sends vs URL),
    # azure, or an empty string
    serviceType: openai

    # must be an OpenAI chat compatible endpoint
    # /chat/completions
    # for serviceType == openai, openai-base64, or azure, url is not needed
    # url: https://api.openai.com/v1
