apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Values.service.name }}-sa-rolebinding"
subjects:
- kind: ServiceAccount
  name: "{{ .Values.service.name }}-sa"
  namespace: "{{ .Values.service.namespace }}"
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io