{{- $ic := include "groundx.layout.ocr.create" . -}}

{{- if eq $ic "true" }}
{{- $ns := include "groundx.ns" . -}}
{{- $svc := include "groundx.layout.serviceName" . -}}
{{- $path := include "groundx.layout.ocr.credentials" . -}}
{{- $hasOCR := include "groundx.layout.hasOCRCredentials" . -}}

{{- if and $path (not (kindIs "string" $path)) -}}
{{- fail "layout.ocr.credentials must be a string path to a file packaged in the chart (e.g., files/ocr/credentials.json)" -}}
{{- end -}}

{{- if eq $hasOCR "true" -}}
  {{- $matches := .Files.Glob $path -}}
  {{- if not $matches -}}
    {{- fail (printf "layout.ocr.credentials file not found at path: %s" $path) -}}
  {{- end -}}
  {{- $blob := .Files.Get $path -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $svc }}-ocr-credentials-map
  namespace: {{ $ns }}
  labels:
{{ include "groundx.renderDefaultLabels" (dict "name" "" "indent" 4 "root" $) }}
data:
  credentials.json: |
    {{ $blob | nindent 4 }}
{{- end }}
{{- end }}
