apiVersion: v1
kind: ConfigMap
metadata:
  name: config-yaml-map
  namespace: {{ include "groundx.ns" . }}
  labels:
{{ include "groundx.renderDefaultLabels" (dict "name" "" "indent" 4 "root" $) }}
data:
  config.yaml: |
    _mysql: &mysql
      ro_addr: {{ include "groundx.db.ro" . }}
      rw_addr: {{ include "groundx.db.rw" . }}
      user: {{ .Values.db.serviceUsername }}
      password: {{ .Values.db.servicePassword }}
      database: {{ .Values.db.dbName }}
      maxIdle: {{ include "groundx.db.maxIdle" . }}
      maxOpen: {{ include "groundx.db.maxOpen" . }}

    ai:
      aws:
        search:
          baseURL: {{ include "groundx.search.baseURL" . }}
          index: {{ .Values.search.indexName }}
          languages:
          {{- range (include "groundx.languages" . | fromYamlArray) }}
            - {{ . }}
          {{- end }}
          username: {{ .Values.search.username  }}
          password: {{ .Values.search.password }}
      eyelevelSearch:
        apiKey: {{ .Values.admin.apiKey }}
        baseURL: {{ include "groundx.ranker.api.serviceUrl" . }}
      layout:
        client:
          apiKey: {{ .Values.admin.apiKey }}
          baseURL: {{ include "groundx.layout.api.serviceUrl" . }}
          callbackURL: {{ include "groundx.layoutWebhook.serviceUrl" . }}
      openai:
        apiKey: {{ include "groundx.summary.apiKey" . }}
        baseURL: {{ include "groundx.summary.baseURL" . }}
        defaultKitId: {{ include "groundx.summary.defaultKitID" . }}
      summaryType: {{ include "groundx.summary.serviceName" . }}
      searchIndexes:
        {{ .Values.search.indexName }}:
          languages:
          {{- range (include "groundx.languages" . | fromYamlArray) }}
            - {{ . }}
          {{- end }}
{{- if and (hasKey .Values.summaryClient "engines") (not (empty .Values.summaryClient.engines)) }}
    engines:
    {{- range $e := .Values.summaryClient.engines }}
      {{ $e.engineID }}:
        engineID: "{{ $e.engineID }}"
        {{- if $e.apiKey }}
        {{ printf "apiKey: %q" $e.apiKey | nindent 8 }}{{ end }}
        {{- if $e.baseURL }}
        {{ printf "baseURL: %q" $e.baseURL | nindent 8 }}{{ end }}
        {{- if hasKey $e "maxInputTokens" }}
        maxInputTokens: {{ $e.maxInputTokens }}{{ end }}
        {{- if hasKey $e "maxRequests"    }}
        maxRequests: {{ $e.maxRequests }}{{ end }}
        {{- if hasKey $e "maxOutputTokens"      }}
        maxTokens: {{ $e.maxOutputTokens }}{{ end }}
        {{- if hasKey $e "requestLimit"   }}
        requestLimit: {{ $e.requestLimit }}{{ end }}
        {{- if $e.type }}
        {{ printf "type: %q" $e.type | nindent 8 }}{{ end }}
        vision: {{ $e.vision | default true }}
    {{- end }}
{{- end }}

    environment: {{ include "groundx.environment" . }}

    groundxServer:
      baseURL: {{ include "groundx.groundx.serviceUrl" . }}
      port: {{ include "groundx.groundx.containerPort" . }}
      serviceName: {{ include "groundx.groundx.serviceName" . }}

    init:
      ingestOnly: {{ include "groundx.ingestOnly" . }}
      mysql:
        user: {{ .Values.db.privilegedUsername }}
        password: {{ .Values.db.privilegedPassword }}
      search:
        password: {{ .Values.search.privilegedPassword }}
        searchModel: all_access
        username: {{ .Values.search.privilegedUsername }}

    integrationTests:
      search:
        duration: {{ include "groundx.integration.search.duration" . }}
        fileId: {{ include "groundx.integration.search.fileId" . | quote }}
        modelId: {{ include "groundx.integration.search.modelId" . }}

    layoutWebhookServer:
      baseURL: {{ include "groundx.layoutWebhook.serviceUrl" . }}
      port: {{ include "groundx.layoutWebhook.containerPort" . }}
      serviceName: {{ include "groundx.layoutWebhook.serviceName" . }}

    kafka:
      filePreProcess:
        broker: {{ printf "%s:%v" (include "groundx.stream.domain" .) (include "groundx.stream.port" .) }}
        groupId: {{ printf "%s-%s" (include "groundx.ns" .) (include "groundx.stream.serviceName" .) }}
        topic: {{ include "groundx.preProcess.queue" . }}
      fileProcess:
        broker: {{ printf "%s:%v" (include "groundx.stream.domain" .) (include "groundx.stream.port" .) }}
        groupId: {{ printf "%s-%s" (include "groundx.ns" .) (include "groundx.stream.serviceName" .) }}
        topic: {{ include "groundx.process.queue" . }}
      fileSummaryDev:
        broker: {{ printf "%s:%v" (include "groundx.stream.domain" .) (include "groundx.stream.port" .) }}
        groupId: {{ printf "%s-%s" (include "groundx.ns" .) (include "groundx.stream.serviceName" .) }}
        topic: {{ include "groundx.summaryClient.queue" . }}
      fileSummaryProd:
        broker: {{ printf "%s:%v" (include "groundx.stream.domain" .) (include "groundx.stream.port" .) }}
        groupId: {{ printf "%s-%s" (include "groundx.ns" .) (include "groundx.stream.serviceName" .) }}
        topic: {{ include "groundx.summaryClient.queue" . }}
      fileUpdate:
        broker: {{ printf "%s:%v" (include "groundx.stream.domain" .) (include "groundx.stream.port" .) }}
        groupId: {{ printf "%s-%s" (include "groundx.ns" .) (include "groundx.stream.serviceName" .) }}
        topic: {{ include "groundx.queue.queue" . }}
      fileUpload:
        broker: {{ printf "%s:%v" (include "groundx.stream.domain" .) (include "groundx.stream.port" .) }}
        groupId: {{ printf "%s-%s" (include "groundx.ns" .) (include "groundx.stream.serviceName" .) }}
        topic: {{ include "groundx.upload.queue" . }}

    metrics:
      active: true
      api:
        - name: {{ include "groundx.groundx.serviceName" . }}
        - name: {{ include "groundx.layout.serviceName" . }}-api
        - name: {{ include "groundx.layoutWebhook.serviceName" . }}
      document:
        tokensPerMinute: {{ include "groundx.throughput.tpm.document" . }}
      inference:
        - name: {{ include "groundx.layout.serviceName" . }}-inference
          tokensPerMinute: {{ include "groundx.throughput.services.layout.inference" . }}
        - name: {{ include "groundx.summary.serviceName" . }}-api
          tokensPerMinute: {{ include "groundx.throughput.services.summary.api" . }}
        - name: {{ include "groundx.summary.serviceName" . }}-inference
          tokensPerMinute: {{ include "groundx.throughput.services.summary.inference" . }}
        - name: {{ include "groundx.summaryClient.serviceName" . }}
          tokensPerMinute: {{ include "groundx.throughput.services.summaryClient.api" . }}
      page:
        tokensPerMinute: {{ include "groundx.throughput.tpm.page" . }}
      queue:
        - name: {{ include "groundx.preProcess.serviceName" . }}
          target: {{ include "groundx.preProcess.queue" . }}
          threshold: {{ include "groundx.throughput.services.preProcess.queue" . }}
        - name: {{ include "groundx.process.serviceName" . }}
          target: {{ include "groundx.process.queue" . }}
          threshold: {{ include "groundx.throughput.services.process.queue" . }}
        - name: {{ include "groundx.queue.serviceName" . }}
          target: {{ include "groundx.queue.queue" . }}
          threshold: {{ include "groundx.throughput.services.queue.queue" . }}
        - name: {{ include "groundx.upload.serviceName" . }}
          target: {{ include "groundx.upload.queue" . }}
          threshold: {{ include "groundx.throughput.services.upload.queue" . }}
      session:
        addr: {{ printf "%s:%v" (include "groundx.metrics.cache.addr" .) (include "groundx.metrics.cache.port" .) }}
        notCluster: {{ include "groundx.metrics.cache.notCluster" . }}
      summaryRequest:
        tokensPerMinute: {{ include "groundx.throughput.tpm.summaryRequest" . }}
      task:
        - name: {{ include "groundx.layout.correct.serviceName" . }}
          target: {{ include "groundx.layout.correct.queue" . }}
          threshold: {{ include "groundx.throughput.services.layout.correct" . }}
        - name: {{ include "groundx.layout.map.serviceName" . }}
          target: {{ include "groundx.layout.map.queue" . }}
          threshold: {{ include "groundx.throughput.services.layout.map" . }}
        - name: {{ include "groundx.layout.ocr.serviceName" . }}
          target: {{ include "groundx.layout.ocr.queue" . }}
          threshold: {{ include "groundx.throughput.services.layout.ocr" . }}
        - name: {{ include "groundx.layout.process.serviceName" . }}
          target: {{ include "groundx.layout.process.queue" . }}
          threshold: {{ include "groundx.throughput.services.layout.process" . }}
        - name: {{ include "groundx.layout.save.serviceName" . }}
          target: {{ include "groundx.layout.save.queue" . }}
          threshold: {{ include "groundx.throughput.services.layout.save" . }}

{{- if .Values.metrics }}
    metricsServer:
      baseURL: http://{{ .Values.metrics.serviceName }}.{{ include "groundx.ns" . }}.svc.cluster.local
      port: {{ .Values.metrics.port }}
      serviceName: {{ .Values.metrics.serviceName }}
      sslCACert: /etc/ssl/tls/ca.crt
      sslCert: /etc/ssl/tls/tls.crt
      sslKey: /etc/ssl/tls/tls.key
      sslPort: 8443
{{- end }}

    owner:
      baseURL: {{ include "groundx.groundx.serviceUrl" . }}/api/v1
      name: on-prem
      type: {{ include "groundx.groundx.type" . }}
      username: {{ .Values.admin.username }}

    preProcessFileServer:
      baseURL: {{ include "groundx.preProcess.serviceUrl" . }}
      maxConcurrent: {{ include "groundx.preProcess.queueSize" . }}
      port: {{ include "groundx.preProcess.containerPort" . }}
      serviceName: {{ include "groundx.preProcess.serviceName" . }}

    processFileServer:
      baseURL: {{ include "groundx.process.serviceUrl" . }}
      maxConcurrent: {{ include "groundx.process.queueSize" . }}
      port: {{ include "groundx.process.containerPort" . }}
      serviceName: {{ include "groundx.process.serviceName" . }}

    processors:
      convert: [11]
      layout: [3]
      map: [4]
      saveFile: [2]
      skipConvert: [12]
      skipGenerate: [1]
      skipLayout: [5]
      skipMap: [6]
      skipSummarize: [7]
      summarize: [8]
      summarizeChunks: [10]
      summarizeSections: [9]
{{- if eq (include "groundx.ingestOnly" .) "true" }}
      extraPostDefaults:
        - processorID: 1
          type: skip-generate
{{- end }}

    queueFileServer:
      baseURL: {{ include "groundx.queue.serviceUrl" . }}
      maxConcurrent: {{ include "groundx.queue.queueSize" . }}
      pollTime: 1
      port: {{ include "groundx.queue.containerPort" . }}
      serviceName: {{ include "groundx.queue.serviceName" . }}

    rec:
      mysql: *mysql
      session:
        addr: {{ printf "%s:%v" (include "groundx.cache.addr" .) (include "groundx.cache.port" .) }}
        notCluster: {{ include "groundx.cache.notCluster" . }}

{{- if .Values.dashboard }}
    ssp:
      baseURL: http://{{ .Values.dashboard.serviceName }}.{{ include "groundx.ns" . }}.svc.cluster.local
      dashboardURL: http://{{ .Values.dashboard.serviceName }}.{{ include "groundx.ns" . }}.svc.cluster.local
{{- end }}

    summaryServer:
      baseURL: {{ include "groundx.summaryClient.serviceUrl" . }}
      maxConcurrent: {{ include "groundx.summaryClient.queueSize" . }}
      port: {{ include "groundx.summaryClient.containerPort" . }}
      serviceName: {{ include "groundx.summaryClient.serviceName" . }}

    {{- $fs := (include "groundx.file.settings" . | fromYaml) }}

    upload:
      baseDomain: {{ get $fs "baseDomain" }}
      baseUrl: {{ printf "%s://%s" (get $fs "scheme") (get $fs "baseDomain") }}
      bucket: {{ get $fs "bucketName" }}
      bucketUrl: {{ printf "%s://%s" (get $fs "bucketScheme") (get $fs "bucketDomain") }}
      id: {{ get $fs "username" }}
      secret: {{ get $fs "password" }}
      service: {{ get $fs "serviceType" }}
      ssl: {{ get $fs "ssl" }}

    uploadFileServer:
      baseURL: {{ include "groundx.upload.serviceUrl" . }}
      maxConcurrent: {{ include "groundx.upload.queueSize" . }}
      port: {{ include "groundx.upload.containerPort" . }}
      serviceName: {{ include "groundx.upload.serviceName" . }}
