{{- $ic := include "groundx.db.create" . -}}
{{- $ec := include "groundx.db.existing" . -}}

{{- if or (eq $ic "true") (eq $ec "true") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-database-file
  namespace: {{ include "groundx.ns" . }}
  labels:
{{ include "groundx.renderDefaultLabels" (dict "name" "" "indent" 4 "root" $) }}
data:
  init-db.sql: |
    INSERT INTO partner_users (customer_username, customer_email, partner_username, status) values ('{{ include "groundx.admin.username" . }}', '{{ include "groundx.admin.email" . }}', '{{ include "groundx.admin.username" . }}', 'admin');

    INSERT INTO apikeys (apikey, name, username) values ('{{ include "groundx.admin.apiKey" . }}', 'Admin Service Key', '{{ include "groundx.admin.username" . }}');

    INSERT INTO processors (name, description, username, ptype, priority) values
    ('Skip Generation', 'Does not add content to search database', 'system', 'skip-generate', 50), ('Save File', 'Saves output to a file', 'system', 'save-file', 50), ('System Document Layout', 'The default document layout processor', 'system', 'layout', 10), ('System Document Layout Mapping', 'The default document layout mapping processor', 'system', 'map', 15), ('Skip Document Layout', 'Does not process documents through layout pipeline', 'system', 'skip-layout', 50), ('Skip Document Mapping Layout', 'Does not map text through pipeline', 'system', 'skip-map', 50), ('Skip Molecule Summarizer', 'Does not summarize molecules in pipeline', 'system', 'skip-summarize', 50), ('System Combined Summarizer', 'The combined default summarizer', 'system', 'summarize', 20), ('System Section Summarizer', 'The default document and page summarizer', 'system', 'summarize-sections', 22), ('System Molecule Summarizer', 'The default molecule summarizer', 'system', 'summarize-chunks', 24), ('System Document Convert', 'The default document convert processor', 'system', 'convert', 7), ('Skip Document Convert', 'Does not convert documents', 'system', 'skip-convert', 50);

    INSERT INTO nlp_models (model_id, name, username, type, settings, indices) values ({{ include "groundx.integration.search.modelId" . }}, 'System Status - Search', '{{ include "groundx.admin.username" . }}', 'gpt3', '{"trainingFilesData":{"mainKit":{"fileId":"{{ include "groundx.integration.search.fileId" . }}","priority":20,"trainingFile":""}}}', '{{ include "groundx.search.indexName" . }}');
{{- end }}
