{{- $svc := include "groundx.layout.serviceName" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $svc }}-gunicorn-conf-py-map
  namespace: {{ include "groundx.ns" . }}
  labels:
{{ include "groundx.renderDefaultLabels" (dict "name" "" "indent" 4 "root" $) }}
data:
  gunicorn_conf.py: |
    infolog = "-"
    accesslog = "-"
    errorlog = "-"

    loglevel = {{ include "groundx.logLevel" . | quote }}
    workers = {{ include "groundx.layout.api.workers" . }}
    threads = {{ include "groundx.layout.api.threads" . }}
    timeout = {{ include "groundx.layout.api.timeout" . }}

    worker_class = "uvicorn.workers.UvicornWorker"

    bind = "0.0.0.0:{{ include "groundx.ranker.api.containerPort" . }}"

    wsgi_app = "document_api_server:app"
