{{- $ns := include "groundx.ns" . -}}
{{- $path := include "groundx.layout.ocr.credentials" . -}}

{{- if and $path (not (kindIs "string" $path)) -}}
{{- fail "layout.ocr.credentials must be a string path to a file packaged in the chart (e.g., files/ocr/credentials.json)" -}}
{{- end -}}

{{- if and (kindIs "string" $path) (ne $path "") -}}
  {{- $matches := .Files.Glob $path -}}
  {{- if not $matches -}}
    {{- fail (printf "layout.ocr.credentials file not found at path: %s" $path) -}}
  {{- end -}}
  {{- $blob := .Files.Get $path -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: layout-ocr-credentials-map
  namespace: {{ $ns }}
  labels:
{{ include "groundx.renderDefaultLabels" (dict "name" "" "indent" 4 "root" $) }}
data:
  credentials.json: |
    {{ $blob | nindent 4 }}
{{- end }}