apiVersion: v1
kind: ConfigMap
metadata:
  name: ranker-config-py-map
  namespace: {{ include "groundx.ns" . }}
  labels:
{{ include "groundx.renderDefaultLabels" (dict "name" "" "indent" 4 "root" $) }}
data:
  config.py: |
    env = dict(
        deviceType={{ .Values.ranker.inference.deviceType | default "cpu" | quote }},
        metricsAddr={{ include "groundx.metrics.cache.addr" . | quote }},
        metricsPort={{ include "groundx.metrics.cache.port" . }},
        searchBroker={{ printf "redis://%s:%v/0" (include "groundx.cache.addr" .) (include "groundx.cache.port" .) | quote }},
        searchLog={{ .Values.ranker.serviceName | quote }},
        searchResultBroker={{ printf "redis://%s:%v/0" (include "groundx.cache.addr" .) (include "groundx.cache.port" .) | quote }},
        service={{ .Values.ranker.serviceName | quote }},
        validAPIKeys=[{{ .Values.admin.apiKey | quote }}, {{ .Values.admin.username | quote }}],
        workers={{ .Values.ranker.inference.workers }},
    )
