{{- $ic := include "groundx.summary.api.create" . -}}
{{- $ec := include "groundx.summary.inference.create" . -}}

{{- if or (eq $ic "true") (eq $ec "true") }}
{{- $svc := include "groundx.summary.serviceName" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $svc }}-config-py-map
  namespace: {{ include "groundx.ns" . }}
  labels:
{{ include "groundx.renderDefaultLabels" (dict "name" "" "indent" 4 "root" $) }}
data:
  config.py: |
    env = dict(
        deviceType={{ include "groundx.summary.inference.deviceType" . | quote }},
        deviceUtilize={{ include "groundx.summary.inference.deviceUtilize" . }},
        metricsAddr={{ include "groundx.metrics.cache.addr" . | quote }},
        metricsPort={{ include "groundx.metrics.cache.port" . }},
        service={{ include "groundx.summary.serviceName" . | quote }},
        summaryBroker={{ printf "redis://%s:%v/0" (include "groundx.cache.addr" .) (include "groundx.cache.port" .) | quote }},
        summaryLog={{ include "groundx.summary.serviceName" . | quote }},
        summaryResultBroker={{ printf "redis://%s:%v/0" (include "groundx.cache.addr" .) (include "groundx.cache.port" .) | quote }},
        validAPIKeys=[{{ include "groundx.admin.apiKey" . | quote }}, {{ include "groundx.admin.username" . | quote }}],
        workers={{ include "groundx.summary.inference.workers" . }},
    )
{{- end }}
