apiVersion: v1
kind: ConfigMap
metadata:
  name: summary-gunicorn-conf-py-map
  namespace: {{ include "groundx.ns" . }}
  labels:
{{ include "groundx.renderDefaultLabels" (dict "name" "" "indent" 4 "root" $) }}
data:
  gunicorn_conf.py: |
    infolog = "-"
    accesslog = "-"
    errorlog = "-"

    loglevel = "{{ .Values.logLevel }}"
    workers = {{ .Values.summary.api.workers }}
    threads = {{ .Values.summary.api.threads }}
    timeout = {{ .Values.summary.api.timeout }}
    timeout_keep_alive = 15

    worker_class = "uvicorn.workers.UvicornWorker"

    bind = "0.0.0.0:8080"

    wsgi_app = "summary_server:app"
