{{- $ic := include "groundx.summary.inference.create" . -}}

{{- if eq $ic "true" }}
{{- $ns := include "groundx.ns" . -}}
{{- $svc := include "groundx.summary.serviceName" . -}}
{{- $workers := int (include "groundx.summary.inference.workers" .) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $svc }}-inference-supervisord-conf-map
  namespace: {{ include "groundx.ns" $ }}
  labels:
{{ include "groundx.renderDefaultLabels" (dict "name" "" "indent" 4 "root" $) }}
data:
  supervisord.conf: |
    [supervisord]
    nodaemon=true
    logfile=/dev/null
    {{- range $i, $_ := until $workers }}

    [program:celery_worker_{{ add $i 1 }}]
    command=celery -A summary.celery_inference.appSummary worker -n %(ENV_POD_NAME)s-w{{ add $i 1 }} --loglevel=INFO --concurrency={{ include "groundx.summary.inference.threads" $ }} --queues={{ include "groundx.summary.inference.queue" $ }} --pool=solo
    environment=
      CELERY_WORKER_NAME="%(ENV_POD_NAME)s-w{{ add $i 1 }}",
      LOCAL="0",
      PYTHONUNBUFFERED="1"
    autostart=true
    autorestart=true
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0
    {{- end }}

    [program:celery_monitor]
    command=python /workspace/summary_monitor.py
    environment=
      LOCAL="0",
      PYTHONUNBUFFERED="1"
    autostart=true
    autorestart=true
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0

    [program:celery_health]
    command=python /workspace/summary_health.py
    environment=
      LOCAL="0",
      PYTHONUNBUFFERED="1"
    autostart=true
    autorestart=true
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0
{{- end }}
